sonar.projectKey=niHoel97_Rockeyboy
sonar.organization=nihoel97
sonar.host.url=https://sonarcloud.io
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
